### PR TITLE
Add build systems

### PR DESCRIPTION
**Pull request by joaopapereira**
Add mvnw and gradlew to the plugin
Add the minimal configuration to make kapt to work with gradle

### CODE REVIEW

**Comment by ctrueden** [comment]
@joaopapereira Thanks! Sorry for my ignorance, but `mvnw` is [this one](https://github.com/takari/maven-wrapper)? I have not used it before... the purpose is to make the build run even for people without the correct version of Maven installed, by bootstrapping it first? Or do I misunderstand?

I have to admit that these wrappers bother me aesthestically from a [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) perspective, since they are copied over so many repositories. But I guess if it improves build accessibility and reproducibility, I shouldn't complain.

**Comment by joaopapereira** [comment]
`mvnw` comes from that repository and as you stated the idea is you do not need to have Maven installed in your machine in order to be able to compile using maven.

Yeah I understand your point of view about the `mvnw` and `gradlew` that are everywhere, but it is more a convenience. These wrappers should be the minimum amount of information possible just to ensure that Maven and Gradle can run.

**Comment by ctrueden** [comment]
OK, thanks @joaopapereira.

By the way: would you be interested in becoming maintainer of this repository? I doubt it would be a lot of work. You'd have more freedom to keep it updated with latest best practices etc., to help others, without needing to wait for me to review.

**Comment by joaopapereira** [comment]
I do not mind that

**Comment by ctrueden** [comment]
@joaopapereira By "I do not mind that" do you mean "I would not mind becoming a maintainer"? Or "I do not mind waiting for PR review from you"?

You can read about SciJava team roles [here](https://imagej.net/Team).

**Pull request merged**
